# Camera
CAMERA_INDEX = 0

# Detection
MAX_HANDS = 2
DETECTION_CONFIDENCE = 0.7
TRACKING_CONFIDENCE = 0.5

# Gesture Recognition
STABLE_FRAMES = 15

# UI
WINDOW_TITLE = "LensFlow"
TEXT_COLOR = (0, 255, 0)
FONT_SCALE = 1
THICKNESS = 2